version: '3.8'

services:
  eczane-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  # ⬅️ BURASI ÖNEMLİ!
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./alerts:/app/alerts

  eczane-frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5000:5000"
    env_file:
      - .env  # ⬅️ BURASI ÖNEMLİ!
    environment:
      - API_URL=http://eczane-backend:8000
    depends_on:
      - eczane-backend